### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by cogmeta** [cw-zift/scio-beast#2]
src/scio_beast.hpp:770:18: error: ‘io_service’ in namespace ‘boost::asio’ does not name a type
src/scio_beast.hpp:820:18: error: ‘io_service’ in namespace ‘boost::asio’ does not name a type
src/scio_beast.hpp:563:22: error: ‘m_ios’ was not declared in this scope
src/scio_beast.hpp: In member function ‘boost::system::error_code scio_beast::SCSocket::close()’:
src/scio_beast.hpp:608:9: error: ‘m_ios’ was not declared in this scope
src/scio_beast.hpp:625:9: error: ‘m_ios’ was not declared in this scope
src/scio_beast.hpp:645:57: error: ‘m_ios’ is not captured
src/scio_beast.hpp:625:9: note: ‘<typeprefixerror>m_ios’ declared here
src/scio_beast.hpp:1100:92: error: ‘m_ios’ was not declared in this scope
src/scio_beast.hpp:1141:9: error: ‘m_ios’ was not declared in this scope
src/scio_beast.hpp: In member function ‘void scio_beast::SCSocket::readSomeHandler(boost::system::error_code)’:

**Comment by cogmeta** [comment]
I am using boost_1_66_0. What version of boost has been tried?

**Comment by NuSkooler** [comment]
@cogmeta This was developed using Boost 1.65. I just looked at the 1.66 release notes, and it looks like `asio::` has been altered quite a bit (and now officially includes Beast!). Try perhaps defining `BOOST_ASIO_ENABLE_OLD_SERVICES` for now.

Note that I am no longer maintaining _this repo_ (See Issue #1 for details). Please feel free to open issues in my fork, and if I have the time I can try to look at them or perhaps upgrade my fork to a full fledged project.

**Comment by cogmeta** [comment]
Thank @NuSkooler. Will try your suggestions and report back.

**Comment by cogmeta** [comment]
@NuSkooler Boost 1.65 did not work as some of the header files are missing. I am trying with 1.65.1 and will see if that is working. Is there any other working c++ client for socketcluster?

**Comment by cogmeta** [comment]
I get this error when tried against 1.65 and 1.65.1
get -nc https://github.com/nlohmann/json/releases/download/v2.1.1/json.hpp
File ‘json.hpp’ already there; not retrieving.

cc -Wall -W -O -std=c++11 -I../../boost_1_65_0/ -I ../../boost_1_65_0/  -I/home/pi/cogmeta/assistant/assistant-cpp/vendor/scio-beast/test -c -o test.o test.cpp
test.cpp:2:32: fatal error: boost/beast/core.hpp: No such file or directory
 #include <boost/beast/core.hpp>

**Comment by cogmeta** [comment]
So i assume beast was not added to boost untll 1.66.0.

**Comment by NuSkooler** [comment]
Correct, you need to supply beast for older versions

**Comment by cogmeta** [comment]
Thanks. Actually, inclusion of Beast in boost makes life easier. We just ended up a creating a websocket stream and implement socketcluster protocol (which is extremely easy and can be found here https://github.com/SocketCluster/socketcluster/blob/master/socketcluster-protocol.md). 

We just needed a synchronous client and it is working fine (without SSL for now). We will add some snippets here just to help others who might be looking for solutions. Meanwhile,  please go through client examples here http://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/examples.html#beast.examples.clients.
